
project_id = "cf84d094-2fdf-4dbb-a705-43884155f694"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[ingest]
enabled = false
port = 54324

[auth]
enabled = true
port = 54325
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://qvntfcjunyegdsdxclpp.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.maps-reverse-geocode]
verify_jwt = false

[functions.maps-geocode]
verify_jwt = false

[functions.maps-directions]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54326
inspector_port = 5432
